#!/bin/sh

batlevel=$(cat /sys/class/power_supply/BAT0/capacity)
brilevel=$(xbacklight -get)
vollevel=$(amixer -c 0 get Master | grep -Eo "[0-9]{1,3}%")
time=$(date +%R)
separator="|"
xsetroot -name "🔈${vollevel}${separator}${time}${separator}${batlevel}%"
#${separator}${brilevel}☀️
